<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./static/assets/forest_road.glb --root /assets/ --types --shadows
Author: Toni García Vilche (https://sketchfab.com/zul_gv)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hiden-road-diorama-ffdfb06b044844848b26b733dfada25f
Title: Hiden Road Diorama
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Road_Road_0: THREE.Mesh
      Ground_Ground_0: THREE.Mesh
      BgCutOut_BackGround_0: THREE.Mesh
      Trees_Nature_0: THREE.Mesh
      Trees_Nature_0_1: THREE.Mesh
      Flowers_Nature_0: THREE.Mesh
      Grass_Nature_0: THREE.Mesh
    }
    materials: {
      Road: THREE.MeshStandardMaterial
      Ground: THREE.MeshStandardMaterial
      BackGround: THREE.MeshStandardMaterial
      Nature: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/assets/forest_road.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group scale={0.01}>
      <T.Group
        position={[-162.7, 17.72, -49.83]}
        rotation={[-Math.PI / 2, 0, 0.69]}
        scale={10.08}
      >
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Trees_Nature_0.geometry}
          material={gltf.materials.Nature}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Trees_Nature_0_1.geometry}
          material={gltf.materials.Nature}
        />
      </T.Group>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Road_Road_0.geometry}
        material={gltf.materials.Road}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Ground_Ground_0.geometry}
        material={gltf.materials.Ground}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={200}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.BgCutOut_BackGround_0.geometry}
        material={gltf.materials.BackGround}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={200}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Flowers_Nature_0.geometry}
        material={gltf.materials.Nature}
        position={[-90.96, -0.13, 3.63]}
        rotation={[-Math.PI, -1.49, -Math.PI / 2]}
        scale={42.47}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Grass_Nature_0.geometry}
        material={gltf.materials.Nature}
        position={[130.87, 13.48, 172.89]}
        rotation={[-0.08, 1.24, 0.21]}
        scale={51.17}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
