<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 forest_road.glb --transform --draco
Author: Toni García Vilche (https://sketchfab.com/zul_gv)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hiden-road-diorama-ffdfb06b044844848b26b733dfada25f
Title: Hiden Road Diorama
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf, useDraco } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/assets/forest_road-transformed.glb', {
    dracoLoader: useDraco()
  })
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group scale={0.01}>
      <T.Group
        position={[-162.7, 17.72, -49.83]}
        rotation={[-Math.PI / 2, 0, 0.69]}
        scale={10.08}
      >
        <T.Mesh
          geometry={gltf.nodes.Trees_Nature_0.geometry}
          material={gltf.materials.Nature}
          castShadow
          receiveShadow
        />
        <T.Mesh
          geometry={gltf.nodes.Trees_Nature_0_1.geometry}
          material={gltf.materials.Nature}
          castShadow
          receiveShadow
        />
      </T.Group>
      <T.Mesh
        geometry={gltf.nodes.Road_Road_0.geometry}
        material={gltf.materials.Road}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Ground_Ground_0.geometry}
        material={gltf.materials.Ground}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={200}
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.BgCutOut_BackGround_0.geometry}
        material={gltf.materials.BackGround}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={200}
      />
      <T.Mesh
        geometry={gltf.nodes.Flowers_Nature_0.geometry}
        material={gltf.materials.Nature}
        position={[-90.96, -0.13, 3.63]}
        rotation={[-Math.PI, -1.49, -Math.PI / 2]}
        scale={42.47}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Grass_Nature_0.geometry}
        material={gltf.materials.Nature}
        position={[130.87, 13.48, 172.89]}
        rotation={[-0.08, 1.24, 0.21]}
        scale={51.17}
        castShadow
        receiveShadow
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
