<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 walking.glb --transform --draco
-->

<script>
  import { Group } from 'three'

  import { T } from '@threlte/core'
  import { useGltf, useGltfAnimations, useDraco } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  ref = new Group()

  const gltf = useGltf('/assets/walking-transformed.glb', {
    dracoLoader: useDraco()
  })

  export const { actions, mixer } = useGltfAnimations(gltf, ref)
</script>

<T
  is={ref}
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Scene">
      <T.Group
        name="Armature"
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <T is={gltf.nodes.mixamorigHips} />
        <T.SkinnedMesh
          name="Ganfaul"
          geometry={gltf.nodes.Ganfaul.geometry}
          material={gltf.materials.Ganfaul_Body}
          skeleton={gltf.nodes.Ganfaul.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
